#!/usr/bin/env bash

# Run in this directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1 

# set the FLAKE_NAME
source _set_flakename.sh || return 1

echo "updating flake ${FLAKE_NAME}"
git add .
sudo nixos-rebuild switch --flake ./#${FLAKE_NAME}
gen=$(nixos-rebuild list-generations | grep current)
git commit -am"flake $FLAKE_NAME: $gen"
echo "running configure ${FLAKE_NAME}"
source configure ${FLAKE_NAME}
