#!/usr/bin/env bash

# Run in this directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1 

# set the FLAKE_NAME
source _set_flakename.sh || return 1

echo "testing flake ${FLAKE_NAME}"
git add .
sudo nixos-rebuild test --fast --flake ./#${FLAKE_NAME}
