--#####################################################################################= hyprctl setcursor Bibata-Modern-Classic 24

--

-- AUTOGENERATED HYPR CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

--autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "pcmanfm"

local menu = "rofi -show drun -show-icons"

local powermenu = "rofi -show power-menu -modi power-menu:rofi-power-menu"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox

-- bar



-- desktop


--exec = swww-daemon &



-- this may bug out 


-- exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibara-Modern-Classic'

-- exec-once=hyprctl setcursor all-scroll 24

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

-- this experimentation doesnt do shit

-- env = XCURSOR_SIZE,24

-- env = HYPRCURSOR_SIZE,24

-- env = XCURSOR_THEME,Bibata-Modern-Ice

-- env = HYPRCURSOR_THEME,Bibata-Modern-Ice

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 8,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "pseudo",
        col = {
            active_border = "rgba(689d6aaa)",
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    group = {
        groupbar = {
			col = {
				active = "rgba(504945ee)",
				inactive = "rgba(282828aa)",
			},
            text_color = "rgba(ebdbb2ee)",
            font_size = 12,
            height = 18,
            rounding = 4,
            indicator_height = 0,
            gradient_rounding = 10,
            round_only_edges = false,
            gradient_round_only_edges = false,
            render_titles = true,
            gradients = true,
        },
        col = {
            border_active = "rgba(689d6aaa)",
            border_inactive = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 0.85,
        -- deprecated
        --drop_shadow = true
        --shadow_range = 4
        --shadow_render_power = 3
        --col.shadow = rgba(1a1a1aee)
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
        -- NAME, ONOFF, SPEED x100ms, CURVE [,STYLE]
    },
})
hl.curve("myBezier", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = false, speed = 6, bezier = "default" })

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "caps:escape,altwin:prtsc_rwin",
        repeat_delay = 250,
        repeat_rate = 60,
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--###################

--## KEYBINDINGSS ###

--###################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

--bind = $mainMod SHIFT, BACKSPACE, exit,

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "BACKSPACE", hl.dsp.exec_cmd("rofi -show power-menu -modi power-menu:rofi-power-menu"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.exec_cmd("pcmanfm"))

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("rofi -show drun -show-icons"))

hl.bind(mainMod .. " + " .. "SUPER_L", hl.dsp.exec_cmd("rofi -show drun -show-icons"))

-- bind = $mainMod, P, pseudo, 

-- bind = $mainMod, V, togglesplit,

hl.bind(mainMod .. " + " .. "T", hl.dsp.group.toggle())

hl.bind(mainMod .. " + " .. "G", hl.dsp.group.toggle())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("gscreenshot"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.window.fullscreen({ mode = 1 }))

-- dwindle

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- change group / tab

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.group.next({ forward = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.group.next())

-- move group / tab

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Left", hl.dsp.group.move_window({ forward = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Right", hl.dsp.group.move_window({ forward = true }))

-- move windows
hl.bind(mainMod .. " + " .. "Left", hl.dsp.window.move({direction = "left", group_aware = true}))
hl.bind(mainMod .. " + " .. "Right", hl.dsp.window.move({direction = "right", group_aware = true}))
hl.bind(mainMod .. " + " .. "Up", hl.dsp.window.move({direction = "up", group_aware = true}))
hl.bind(mainMod .. " + " .. "Down", hl.dsp.window.move({direction = "down", group_aware = true}))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 , follow = false}))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 , follow = false}))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- brightnessctl

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s +10%"))

-- Example volume button that allows press and hold, volume limited to 150%

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })

-- Example volume button that will activate even while an input inhibitor is active

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

--

-- Example special workspace (scratchpad)

-- bind = $mainMod, S, togglespecialworkspace, magic

-- bind = $mainMod SHIFT, S, movetoworkspace, special:magic

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- in fullscreen, disable rounding and borders

hl.window_rule({
    name  = "rounding_0_341",
    match = {
        fullscreen = 1,
    },
    rounding = 0,
})

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.exec_cmd("pkill waybar")
    hl.exec_cmd("waybar &")
    hl.exec_cmd("swww kill")
    hl.exec_cmd("swww init")
    hl.exec_cmd("swww img./cheslen.jpg")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
end)
